### PR TITLE
doc: Bootstrap with some initial things for discussion.

### PR DESCRIPTION
**Pull request by Fishrock123**
Please do not discuss all possibilities in the PR. This is for bootstrapping discussions.

If it seems roughly ok with everyone I'll merge and we can start basing PRs against it to modify / add / remove from the Design Doc.

cc @nodejs/CI (Moving from https://github.com/nodejs/build/issues/257)

### CODE REVIEW

**Comment by cjihrig** [comment]
LGTM as a starting point

**Comment by targos** [comment]
LGTM

**Comment by rmg** [comment]
LGTM :+1:

**Comment by jasnell** [comment]
LGTM

**Pull request merged**
